export const API_FETCHING = "API_FETCHING";
export const API_RETRIEVED = "API_RETRIEVED"; 
export const API_RETRIEVED_WITH_NO_DATA = "API_RETRIEVED_WITH_NO_DATA";
export const API_CONNECTION_ERROR = "API_CONNECTION_ERROR";
export const API_ERROR = "API_ERROR";